# Generated by Django 2.2.4 on 2019-08-20 21:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MediaManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 8, 21, 1, 12, 19, 215974))),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fakultet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shortname', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('created', models.DateField(verbose_name='Ստեղծման Տարի')),
            ],
        ),
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=25)),
                ('workstarteddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'worker',
                'verbose_name_plural': 'Workers',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=36)),
                ('lastName', models.CharField(max_length=72)),
                ('hayranun', models.CharField(max_length=36)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('joindate', models.DateField()),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('petpatver', models.BooleanField(default=False)),
                ('studyprice', models.IntegerField(default=0)),
                ('phone', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.group')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MediaManagement.Image')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tareketum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.IntegerField(verbose_name='Տարկետման սեմեստր')),
                ('length', models.IntegerField(verbose_name='Ժամկետ')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.IntegerField()),
                ('lessons', models.IntegerField(verbose_name='Սեմեստրի լեկցիաների քանակը')),
                ('lecturers', models.ManyToManyField(to='university.staff')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.WorkerType'),
        ),
        migrations.CreateModel(
            name='profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('years', models.IntegerField()),
                ('heraka', models.BooleanField(blank=True, default=False, verbose_name='հեռակա')),
                ('fakultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.fakultet')),
                ('subjects', models.ManyToManyField(to='university.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.PointType')),
            ],
        ),
        migrations.CreateModel(
            name='matyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loose', models.BooleanField(default=True)),
                ('minute', models.IntegerField()),
                ('date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='lecturers',
            field=models.ManyToManyField(to='university.staff'),
        ),
        migrations.AddField(
            model_name='group',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.profession'),
        ),
        migrations.AddField(
            model_name='fakultet',
            name='dekan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='university.staff'),
        ),
        migrations.AddField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.group'),
        ),
        migrations.AddField(
            model_name='exam',
            name='lacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='university.staff'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.ExamType'),
        ),
        migrations.CreateModel(
            name='ambion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('shortname', models.CharField(max_length=50)),
                ('teachers', models.ManyToManyField(related_name='ambionteacher', to='university.staff')),
                ('varich', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambionvarich', to='university.staff')),
            ],
        ),
    ]
